---
# Set necessary role variables

#- import_tasks: tasks/generate_tmp/generate_tmp.yml

## JDK 11

- name: Set general internal variables for java 11
  set_fact:
    jdk_version: "{{ java_version }}.{{ java_subversion }}"
  when: java_version == 11

## JDK 10

- name: Set java subversion for java 10
  set_fact:
    # JDK 10 is only available in 10.0.2
    java_subversion: 0.2
  when: java_version == 10

- name: Set general internal variables for java 10
  set_fact:
    jdk_version: "{{ java_version }}.{{ java_subversion }}"
  when: java_version == 10

## JDK 9

- name: Set Java subversion java 9
  set_fact:
    # JDK 9 is only available in 9.0.4
    java_subversion: 0.4
  when: java_version == 9

- name: Set general internal variables for java 9
  set_fact:
    jdk_version: "{{ java_version }}.{{ java_subversion }}"
  when: java_version == 9

## JDK 8

- name: Set general internal variables for java 8
  set_fact:
    jdk_version: "1.{{ java_version }}.0_{{ java_subversion }}"
  when: java_version == 8


# Architecture & platform-specific variables

- name: Set Java architecture
  set_fact:
    jdk_arch: "{{ 'i586' if ansible_architecture == 'i386' else 'x64' }}"

# OS

- name: Set Java OS for Linux
  set_fact:
    jdk_os: linux
  when: ansible_system == 'Linux'

- name: Set Java OS for Mac OS X
  set_fact:
    jdk_os: macosx
  when: ansible_os_family == 'Darwin'

- name: Set Java OS for Mac OS X
  set_fact:
    jdk_os: osx
  when: ansible_os_family == 'Darwin' and jdk_version == 9

# Installation binary

- name: Set RPM binary
  set_fact:
    use_rpm: true
    use_tarball: false
    use_dmg: false
    install_file_extension: rpm
  when: (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "zypper") and ansible_os_family != 'Darwin'

- name: Set Gzipped Tarball binary
  set_fact:
    use_tarball: true
    use_rpm: false
    use_dmg: false
    install_file_extension: tar.gz
  when: ansible_pkg_mgr != "yum" and ansible_pkg_mgr != "zypper" and ansible_os_family != "Darwin"

- name: Set dmg binary
  set_fact:
    use_dmg: true
    use_rpm: false
    use_tarball: false
    install_file_extension: dmg
  when: ansible_pkg_mgr != "yum" and ansible_pkg_mgr != "zypper" and ansible_os_family == "Darwin"

## Version-specific variables
# JDK 11

- name: Set internal variables for 11
  set_fact:
    jdk_version_detail: "{{ java_version }}.{{ java_subversion }}+13"
    jdk_tarball_hash: 90cf5d8f270a4347a95050320eef3fb7
  when: java_version == 11

# JDK 10

- name: Set internal variables for 10
  set_fact:
    java_subversion: 0.2
    jdk_version_detail: "{{ java_version }}.{{ java_subversion }}+13"
    jdk_tarball_hash: 19aef61b38124481863b1413dce1855f
  when: java_version == 10

## JDK 9
# Only available for download with oracle account (not supported by this role)!

- name: Set internal variables for 9.0.4
  set_fact:
    java_subversion: 0.4
    jdk_version_detail: "{{ java_version }}.{{ java_subversion }}+11"
    jdk_tarball_hash: c2514751926b4512b076cc82f959763f
  when: java_version == 9

## JDK 8

- name: set internal variables for 1.8.0_191
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b12"
    jdk_tarball_hash: 2787e4a523244c269598db4e85c51e0c
  when: java_version == 8 and java_subversion == 191

# All versions below are only available for download with an oracle account (not supported by this role)!

- name: set internal variables for 1.8.0_181
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b13"
    jdk_tarball_hash: 96a7b8442fe848ef90c96a2fad6ed6d1
  when: java_version == 8 and java_subversion == 181

- name: Set internal variables for 1.8.0_172
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b11"
    jdk_tarball_hash: a58eab1ec242421181065cdc37240b08
  when: java_version == 8 and java_subversion == 172

- name: Set internal variables for 1.8.0_171
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b11"
    jdk_tarball_hash: 512cd62ec5174c3487ac17c61aaa89e8
  when: java_version == 8 and java_subversion == 171

- name: Set internal variables for 1.8.0_161
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b12"
    jdk_tarball_hash: 2f38c3b165be4555a1fa6e98c45e0808
  when: java_version == 8 and java_subversion == 161

- name: Set internal variables for 1.8.0_152
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b16"
    jdk_tarball_hash: aa0333dd3019491ca4f6ddbe78cdb6d0
  when: java_version == 8 and java_subversion == 152

- name: Set internal variables for 1.8.0_151
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b12"
    jdk_tarball_hash: e758a0de34e24606bca991d704f6dcbf
  when: java_version == 8 and java_subversion == 151

- name: Set internal variables for 1.8.0_141
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b15"
    jdk_tarball_hash: 336fa29ff2bb4ef291e347e091f7f4a7
  when: java_version == 8 and java_subversion == 141

- name: Set internal variables for 1.8.0_131
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b11"
    jdk_tarball_hash: d54c1d3a095b4ff2b6607d096fa80163
  when: java_version == 8 and java_subversion == 131

- name: Set internal variables for 1.8.0_121
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b13"
    jdk_tarball_hash: e9e7ea248e2c4826b92b3f075a80e441
  when: java_version == 8 and java_subversion == 121

- name: Set internal variables for 1.8.0_111
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b14"
  when: java_version == 8 and java_subversion == 111

- name: Set internal variables for generic Java version
  set_fact:
    jdk_version_detail: "{{ java_version }}u{{ java_subversion }}-b{{ java_build }}"
  when: jdk_version_detail is not defined and java_build is defined

- name: Compose filename only if necessary
  set_fact:
    jdk_file_name: "jdk-{{ java_version }}u{{ java_subversion }}-{{ jdk_os }}-{{ jdk_arch }}"
  when: jdk_file_name is not defined and java_version == 8

- name: Compose filename only if necessary
  set_fact:
    jdk_file_name: "jdk-{{ java_version }}.{{ java_subversion }}_{{ jdk_os }}-{{ jdk_arch }}_bin"
  when: jdk_file_name is not defined and java_version != 8

- name: Compose URL for downloading file only if necessary1
  set_fact:
    jdk_file_url: "{{ java_mirror }}/{{ jdk_version_detail }}/{{ jdk_file_name }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is not defined

- name: Compose url for downloading file only if necessary2
  set_fact:
    jdk_file_url: "{{ java_mirror }}/{{ jdk_version_detail }}/{{ jdk_tarball_hash }}/{{ jdk_file_name }}"
  when: jdk_version_detail is defined and jdk_tarball_hash is defined

# JCE variables

- name: Set JCE zip file variables for Java 8
  set_fact:
    jce_zip_file: "jce_policy-{{ java_version }}.zip"
  when: java_version == 8

- name: Set JCE variables for Java 8
  set_fact:
    jce_zip_url: "{{ java_mirror }}/jce/{{ java_version }}/{{ jce_zip_file }}"
    jce_zip_folder: "UnlimitedJCEPolicyJDK{{ java_version }}"
  when: java_version == 8

# JDKs greater than 8 do not need JCE anymore

- name: Set JCE download file
  set_fact:
    java_install_jce: false
    jce_zip_file:   ""
    jce_zip_url: ""
    jce_zip_folder: ""
  when: java_version != 8

# Directories

- name: Set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
    java_home: /usr/lib/jvm/default-java
  when: ansible_os_family == "Debian"

- name: Set java installation directory on Mac OS X
  set_fact:
    # The Java installation directory on Mac OS X is determined by the package itself.
    java_install_dir: /no_such_directory
    java_default_link_name: default
  when: ansible_os_family == "Darwin"

- name: Set java installation directory on non-Debian platforms
  set_fact:
    java_install_dir: /usr/java
    java_default_link_name: default
    java_home: /usr/java/default
  when: ansible_os_family != "Debian" and ansible_os_family != "Darwin"
